# Generated by Django 4.2.6 on 2024-03-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='catagory',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
