# Generated by Django 4.2.6 on 2024-03-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0002_brand_is_listed_catagory_is_listed"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="is_deleted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="catagory",
            name="is_deleted",
            field=models.BooleanField(default=True),
        ),
    ]
