# Generated by Django 5.0.3 on 2024-05-11 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Admin", "0004_remove_brand_is_deleted_remove_catagory_is_deleted"),
        ("Products", "0009_alter_wishlist_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[("category", "Category"), ("product", "Product")],
                        max_length=10,
                    ),
                ),
                ("discount_percentage", models.PositiveIntegerField()),
                ("new_price", models.PositiveIntegerField(default=0)),
                ("old_price", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.catagory",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Products.product",
                    ),
                ),
            ],
        ),
    ]
