# Generated by Django 5.0.3 on 2024-05-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Offer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
