# Generated by Django 5.0.3 on 2024-06-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Offer", "0002_offer_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="new_price",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="old_price",
        ),
    ]
