# Generated by Django 5.0.3 on 2024-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Userapp", "0002_wallet_wallet_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="referal_code",
            field=models.CharField(default=None, max_length=25, null=True, unique=True),
        ),
    ]
