# Generated by Django 5.0.3 on 2024-04-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
