# Generated by Django 5.0.3 on 2024-05-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
