# Generated by Django 5.0.3 on 2024-05-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="shipping_charge",
            field=models.BooleanField(default=False),
        ),
    ]
