# Generated by Django 5.0.3 on 2024-04-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0001_initial"),
        ("Products", "0009_alter_wishlist_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.color_products",
            ),
        ),
    ]
