# Generated by Django 5.0.3 on 2024-04-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0003_alter_orderproduct_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="trackig_id",
            field=models.CharField(default=None, max_length=20, null=True, unique=True),
        ),
    ]
