# Generated by Django 5.0.3 on 2024-04-29 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0005_payment_status"),
        ("Products", "0009_alter_wishlist_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="size",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.size_variant",
            ),
        ),
    ]
