# Generated by Django 5.0.3 on 2024-04-29 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0006_orderproduct_size"),
        ("cart", "0005_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="Address",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.address",
            ),
        ),
    ]
