# Generated by Django 5.0.3 on 2024-05-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0008_rename_trackig_id_order_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="Address",
        ),
        migrations.AddField(
            model_name="order",
            name="House_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pincode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
