# Generated by Django 5.0.3 on 2024-05-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0009_remove_order_address_order_house_no_order_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="request_status",
            field=models.CharField(default="None", max_length=20, null=True),
        ),
    ]
