# Generated by Django 5.0.3 on 2024-05-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0010_orderproduct_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="request_status",
            field=models.CharField(default="None", max_length=30, null=True),
        ),
    ]
