# Generated by Django 5.0.3 on 2024-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0011_alter_orderproduct_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="Transaction_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
