# Generated by Django 5.0.3 on 2024-05-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0012_payment_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
