# Generated by Django 5.0.3 on 2024-05-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0013_orderproduct_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="min_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
