# Generated by Django 5.0.3 on 2024-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0014_order_coupon_amount_order_min_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_charge",
            field=models.BooleanField(default=False),
        ),
    ]
