# Generated by Django 5.0.3 on 2024-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0015_order_shipping_charge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("COD", "Cash on Delivery"),
                    ("Razorpay", "Razorpay"),
                    ("Wallet", "Wallet"),
                ],
                max_length=20,
            ),
        ),
    ]
