# Generated by Django 4.2.6 on 2024-03-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0005_remove_product_thumbnail_color_products_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="color_products",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
