# Generated by Django 5.0.3 on 2024-04-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0008_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="products",
            field=models.ManyToManyField(
                related_name="wishlists", to="Products.color_products"
            ),
        ),
    ]
