# Generated by Django 5.0.3 on 2024-05-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0009_alter_wishlist_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="offer_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
